// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package callback

import (
	"github.com/ayflying/utility_go/api/callback"
)

type ControllerV1 struct{}

func NewV1() callback.ICallbackV1 {
	return &ControllerV1{}
}
