# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    ctrl:
      dstFolder: "controller"
    service:
      dstFolder: "service"
    pb:
      path: "manifest/protobuf"
      api: "api"
      ctrl: "controller"
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - "hub.docker.com"
#      - "git.7cuu.com"
    tag: "latest"