// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.0
// source: pkg/v1/pkg.proto

package v1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义 NoticeType 枚举
type NoticeType int32

const (
	NoticeType_DINGTALK NoticeType = 0
	NoticeType_WECHAT   NoticeType = 1
	NoticeType_EMAIL    NoticeType = 2
	NoticeType_SMS      NoticeType = 3
	NoticeType_VOICE    NoticeType = 4
)

// Enum value maps for NoticeType.
var (
	NoticeType_name = map[int32]string{
		0: "DINGTALK",
		1: "WECHAT",
		2: "EMAIL",
		3: "SMS",
		4: "VOICE",
	}
	NoticeType_value = map[string]int32{
		"DINGTALK": 0,
		"WECHAT":   1,
		"EMAIL":    2,
		"SMS":      3,
		"VOICE":    4,
	}
)

func (x NoticeType) Enum() *NoticeType {
	p := new(NoticeType)
	*p = x
	return p
}

func (x NoticeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NoticeType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_v1_pkg_proto_enumTypes[0].Descriptor()
}

func (NoticeType) Type() protoreflect.EnumType {
	return &file_pkg_v1_pkg_proto_enumTypes[0]
}

func (x NoticeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NoticeType.Descriptor instead.
func (NoticeType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_v1_pkg_proto_rawDescGZIP(), []int{0}
}

// 排行榜数据
type RankData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Score    int64 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Rank     int32 `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	UpdateTs int64 `protobuf:"varint,4,opt,name=update_ts,json=updateTs,proto3" json:"update_ts,omitempty"`
}

func (x *RankData) Reset() {
	*x = RankData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_v1_pkg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RankData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankData) ProtoMessage() {}

func (x *RankData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_v1_pkg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankData.ProtoReflect.Descriptor instead.
func (*RankData) Descriptor() ([]byte, []int) {
	return file_pkg_v1_pkg_proto_rawDescGZIP(), []int{0}
}

func (x *RankData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RankData) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RankData) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *RankData) GetUpdateTs() int64 {
	if x != nil {
		return x.UpdateTs
	}
	return 0
}

var File_pkg_v1_pkg_proto protoreflect.FileDescriptor

var file_pkg_v1_pkg_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x6b, 0x67, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x22, 0x61, 0x0a, 0x08, 0x52,
	0x61, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x61, 0x6e,
	0x6b, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x73, 0x2a, 0x45,
	0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08,
	0x44, 0x49, 0x4e, 0x47, 0x54, 0x41, 0x4c, 0x4b, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x45,
	0x43, 0x48, 0x41, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x4d, 0x41, 0x49, 0x4c, 0x10,
	0x02, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x4d, 0x53, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x4f,
	0x49, 0x43, 0x45, 0x10, 0x04, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x79, 0x66, 0x6c, 0x79, 0x69, 0x6e, 0x67, 0x2f, 0x75, 0x74, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x5f, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_v1_pkg_proto_rawDescOnce sync.Once
	file_pkg_v1_pkg_proto_rawDescData = file_pkg_v1_pkg_proto_rawDesc
)

func file_pkg_v1_pkg_proto_rawDescGZIP() []byte {
	file_pkg_v1_pkg_proto_rawDescOnce.Do(func() {
		file_pkg_v1_pkg_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_v1_pkg_proto_rawDescData)
	})
	return file_pkg_v1_pkg_proto_rawDescData
}

var file_pkg_v1_pkg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_v1_pkg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_v1_pkg_proto_goTypes = []interface{}{
	(NoticeType)(0),  // 0: package.NoticeType
	(*RankData)(nil), // 1: package.RankData
}
var file_pkg_v1_pkg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_v1_pkg_proto_init() }
func file_pkg_v1_pkg_proto_init() {
	if File_pkg_v1_pkg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_v1_pkg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RankData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_v1_pkg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_v1_pkg_proto_goTypes,
		DependencyIndexes: file_pkg_v1_pkg_proto_depIdxs,
		EnumInfos:         file_pkg_v1_pkg_proto_enumTypes,
		MessageInfos:      file_pkg_v1_pkg_proto_msgTypes,
	}.Build()
	File_pkg_v1_pkg_proto = out.File
	file_pkg_v1_pkg_proto_rawDesc = nil
	file_pkg_v1_pkg_proto_goTypes = nil
	file_pkg_v1_pkg_proto_depIdxs = nil
}
